timeout: 1200s
logsBucket: 'vodaf-hack25dus-903-logging'
options:
  workerPool: projects/vodaf-hack25dus-903/locations/us-central1/workerPools/pool1

steps:
  # List GCS bucket.
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
    - 'ls'
    - '-l'
    - 'gs://staging-hack-903'

  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']
  - name: python
    entrypoint: python
    args: ['-m', 'pip', 'install', 'build', 'pytest', 'Flask', '--user']
  - name: python
    entrypoint: python
    args: ['call_agent.py']
